[DSTEW-1490] - Initial Submit
* [DSTEW-1490] - Run init script and fix tests

* [DSTEW-1490] - Add Snyk shortlived token

* [DSTEW-1490] - change token env var

* [DSTEW-1490] - set env with Oath token for other steps

* [DSTEW-1490] - Update codeowners

diff --git a/.github/workflows/pr-merge-main.yml b/.github/workflows/pr-merge-main.yml
--- a/.github/workflows/pr-merge-main.yml
+++ b/.github/workflows/pr-merge-main.yml
@@ -38,7 +38,7 @@ jobs:
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: test-results
-          path: spring-boot-microservice-service/build/test-results
+          path: laa-data-claims-certificated-service/build/test-results
           retention-days: 14
 
       - name: Upload checkstyle report
@@ -46,7 +46,7 @@ jobs:
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: checkstyle-report
-          path: spring-boot-microservice-service/build/reports/checkstyle
+          path: laa-data-claims-certificated-service/build/reports/checkstyle
           retention-days: 14
 
       - name: Upload test report
@@ -54,7 +54,7 @@ jobs:
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: test-report
-          path: spring-boot-microservice-service/build/reports/tests
+          path: laa-data-claims-certificated-service/build/reports/tests
           retention-days: 14
 
       - name: Upload jacoco coverage report
@@ -62,7 +62,7 @@ jobs:
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: jacoco-coverage-report
-          path: spring-boot-microservice-service/build/reports/jacoco
+          path: laa-data-claims-certificated-service/build/reports/jacoco
           retention-days: 14
 
   vulnerability-report:
@@ -83,6 +83,24 @@ jobs:
         with:
           java-version: 25
           distribution: 'corretto'
+
+      - name: Obtain Short-lived Snyk token
+        id: auth
+        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/snyk-auth@6db001458db30ae747d9eb8eb25707ce52b359bc
+        with:
+          client_id: ${{ secrets.SNYK_CLIENT_ID }}
+          client_secret: ${{ secrets.SNYK_CLIENT_SECRET }}
+
+      - name: Export Snyk token for remaining steps
+        shell: bash
+        run: |
+          TOKEN='${{ steps.auth.outputs.token }}'
+          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
+            echo "::error::snyk-auth returned empty/null token"
+            exit 1
+          fi
+          echo "::add-mask::$TOKEN"
+          echo "SNYK_OAUTH_TOKEN=$TOKEN" >> "$GITHUB_ENV"
 
       - name: Setup Snyk
         uses: snyk/actions/setup@master
